apiVersion: apps/v1
kind: Deployment
metadata:
  name: pluralkit-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pluralkit-api
  template:
    metadata:
      labels:
        app: pluralkit-api
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '9000'
    spec:
      containers:
      - name: dotnet-api
        # this needs to go in containers for some reason, so we put it in the first one
        resources:
          requests:
            cpu: 1
        image: ghcr.io/pluralkit/pluralkit:85b2b77730146d80c0943eb35f2d11674256ff28
        command: [ "dotnet", "bin/PluralKit.API.dll" ]
        env:
        - name: PluralKit__Api__ClientId
          value: '912009351160541225'
        - name: PluralKit__Api__ClientSecret
          valueFrom:
            secretKeyRef:
              name: discord-client-secret
              key: credential
        - name: PluralKit__DatabasePassword
          valueFrom:
            secretKeyRef:
              name: database-password
              key: credential
        - name: PluralKit__SentryUrl
          valueFrom:
            secretKeyRef:
              name: beta-sentry-url
              key: credential
        - name: PluralKit__Api__TrustAuth
          value: 'true'
        - name: PluralKit__Database
          value: "Host=database-node1-bd9aa148.vpn.pluralkit.net;Port=5432;Username=beta;Database=beta;Maximum Pool Size=150;Minimum Pool Size = 50;Max Auto Prepare=50"
        - name: PluralKit__RedisAddr
          value: "database-node1-bd9aa148.vpn.pluralkit.net:6379,abortConnect=false"
        - name: PluralKit__DispatchProxyUrl
          value: "http://dispatch.svc.pluralkit.net"
        - name: PluralKit__DispatchProxyToken
          valueFrom:
            secretKeyRef:
              name: dispatch-proxy-token
              key: credential
        - name: PluralKit__ConsoleLogLevel
          value: '2'
        - name: PluralKit__ElasticLogLevel
          value: '2'
        - name: PluralKit__FileLogLevel
          value: '5'
        - name: PluralKit__Api__SearchGuildSettings
          value: 'true'

      - name: rust-api
        image: ghcr.io/pluralkit/api:2e3172df35dc3c20767bee849997f65966d951fe
        env:
        - name: RUST_LOG
          value: info
        - name: pluralkit__json_log
          value: "true"
        - name: pluralkit__run_metrics_server
          value: "true"
        - name: pluralkit__sentry_url
          valueFrom:
            secretKeyRef:
              name: beta-sentry-url
              key: credential
        - name: pluralkit__db__data_db_uri
          value: "postgresql://beta@database-node1-bd9aa148.vpn.pluralkit.net:5432/beta"
        - name: pluralkit__db__db_password
          valueFrom:
            secretKeyRef:
              name: database-password
              key: credential
        - name: pluralkit__db__data_redis_addr
          value: "redis://database-node1-bd9aa148.vpn.pluralkit.net:6379/2"
        - name: pluralkit__api__ratelimit_redis_addr
          value: "redis://database-node1-bd9aa148.vpn.pluralkit.net:6379/2"
        - name: pluralkit__api__addr
          value: '[::]:5001'
        - name: pluralkit__api__remote_url
          value: "http://localhost:5000"
        - name: pluralkit__api__temp_token2
          valueFrom:
            secretKeyRef:
              name: api-token2
              key: credential
---
apiVersion: v1
kind: Service
metadata:
  name: pluralkit-api
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: api
    port: 80
    protocol: TCP
    targetPort: 5001
  selector:
    app: pluralkit-api
  type: ClusterIP
