apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: database-password
spec:
  itemPath: vaults/rx2ztehn4uge4qfweepanvihhq/items/zd2wqzr2elvhbyszbxuisd4ane
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dispatch-proxy-token
spec:
  itemPath: vaults/acnop6sxzggtzwha2bulnpjj6i/items/wpva5y45t2zyvvatzedflodp3i
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: discord-token
spec:
  itemPath: "vaults/rx2ztehn4uge4qfweepanvihhq/items/pr6sdwkaju2jzhwmtqt5ixfj6m"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: beta-sentry-url
spec:
  itemPath: vaults/rx2ztehn4uge4qfweepanvihhq/items/zcmly3vmtasljv44milgulfdxy
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: api-token2
spec:
  itemPath: vaults/rx2ztehn4uge4qfweepanvihhq/items/uznhpjmn7wteakt2nedxp26hge
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: discord-client-secret
spec:
  itemPath: vaults/rx2ztehn4uge4qfweepanvihhq/items/igue5r7wqfeutvnoqiij7wsefm
