apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: avatars-sentry-url
spec:
  itemPath: vaults/acnop6sxzggtzwha2bulnpjj6i/items/2as6sgd6uwskp63ojkz7ysp3li
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: avatars-r2-key
spec:
  itemPath: vaults/acnop6sxzggtzwha2bulnpjj6i/items/ilulelqu74hoschnwlisiknqh4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pluralkit-avatars
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pluralkit-avatars
  template:
    metadata:
      labels:
        app: pluralkit-avatars
    spec:
      containers:
      - name: avatars
        image: ghcr.io/pluralkit/avatars:049f06d9b1f75d4ab73323120287703607d3c86a
        env:
        - name: RUST_LOG
          value: info
        - name: pluralkit__json_log
          value: "true"
        - name: pluralkit__sentry_url
          valueFrom:
            secretKeyRef:
              name: avatars-sentry-url
              key: credential
        - name: pluralkit__db__data_db_uri
          value: 'postgresql://pluralkit@[fdaa:9:e856:a7b:910f:0:a:102]:5432/pluralkit'
        - name: pluralkit__db__db_password
          valueFrom:
            secretKeyRef:
              name: database-password
              key: credential
        - name: pluralkit__avatars__cdn_url
          value: 'https://cdn.pluralkit.me/'
        - name: pluralkit__avatars__s3__bucket
          value: 'pluralkit-avatars-2'
        - name: pluralkit__avatars__s3__endpoint
          value: 'https://34d8c1092fc4c5853b6a5a05b08228c5.r2.cloudflarestorage.com'
        - name: pluralkit__avatars__s3__application_id
          value: 'cedf19445910ca54744d8ac0f1a4e7a0'
        - name: pluralkit__avatars__s3__application_key
          valueFrom:
            secretKeyRef:
              name: avatars-r2-key
              key: credential
        - name: pluralkit__db__data_redis_addr
          value: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: pluralkit-avatars
spec:
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
  ports:
  - name: avatars
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: pluralkit-avatars
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pluralkit-avatar-cleanup
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pluralkit-avatar-cleanup
  template:
    metadata:
      labels:
        app: pluralkit-avatar-cleanup
    spec:
      containers:
      - name: avatars
        resources:
          requests:
            cpu: 2
        image: ghcr.io/pluralkit/avatars:049f06d9b1f75d4ab73323120287703607d3c86a
        command: [ "/bin/avatar_cleanup" ]
        env:
        - name: RUST_LOG
          value: info
        - name: pluralkit__json_log
          value: "true"
        - name: pluralkit__sentry_url
          valueFrom:
            secretKeyRef:
              name: avatars-sentry-url
              key: credential
        - name: pluralkit__db__data_db_uri
          value: 'postgresql://pluralkit@[fdaa:9:e856:a7b:910f:0:a:102]:5432/pluralkit'
        - name: pluralkit__db__db_password
          valueFrom:
            secretKeyRef:
              name: database-password
              key: credential
        - name: pluralkit__avatars__cdn_url
          value: 'https://cdn.pluralkit.me/'
        - name: pluralkit__avatars__s3__bucket
          value: 'pluralkit-avatars-2'
        - name: pluralkit__avatars__s3__endpoint
          value: 'https://34d8c1092fc4c5853b6a5a05b08228c5.r2.cloudflarestorage.com'
        - name: pluralkit__avatars__s3__application_id
          value: 'cedf19445910ca54744d8ac0f1a4e7a0'
        - name: pluralkit__avatars__s3__application_key
          valueFrom:
            secretKeyRef:
              name: avatars-r2-key
              key: credential
        - name: pluralkit__db__data_redis_addr
          value: '1'
